repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
    exclude: |
        (?x)(
            ^docs/|
            ^vendor/
        )
  - id: trailing-whitespace
    exclude: |
        (?x)(
            ^docs/|
            ^vendor/
        )
  - id: check-case-conflict
    exclude: |
        (?x)(
            ^docs/|
            ^vendor/
        )
  - id: check-merge-conflict
    exclude: ^vendor/
  - id: detect-private-key
- repo: https://github.com/golangci/golangci-lint
  rev: v1.63.4
  hooks:
    - id: golangci-lint
      files: ntopng/
      exclude: ^vendor/
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.1
  hooks:
    - id: go-fmt
      exclude: ^vendor/
- repo: https://github.com/FalcoSuessgott/tfplugindocs
  rev: v0.0.2
  hooks:
    - id: tfplugindocs
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.96.3
  hooks:
    - id: terraform_fmt
      files: _examples/
- repo: local
  hooks:
    - id: not-using-valid-secret-placeholders
      name: not-using-valid-secret-placeholders
      entry: bash -c "lines=$(grep -rE 'NTOPNG_USERNAME=|NTOPNG_TOKEN=' | grep -vEInH 'your-username|your-token' | wc -l) && (( $lines >= 1 )) && exit 1 || :"
      language: system
      pass_filenames: false
